services:

  # ==========================================
  # SERVIDOR DE DESCUBRIMIENTO EUREKA
  # ==========================================
  eureka-server:
    build: ./eureka
    container_name: eureka-server
    ports:
      - "8761:8761"

  # ==========================================
  # MICROSERVICIO DE PACIENTE
  # ==========================================
  cyber-patient-service:
    build: ./cyber-patient-service
    container_name: cyber-patient-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server

  # ==========================================
  # MICROSERVICIO DE CIBERWARE
  # ==========================================
  cyber-ciberware-service:
    build: ./cyber-ciberware-service
    container_name: cyber-ciberware-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server

  # ==========================================
  # MICROSERVICIO DE SALE
  # ==========================================
  cyber-sale-service:
    build: ./cyber-sale-service
    container_name: cyber-sale-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server

  # ==========================================
  # MICROSERVICIO DE FINANCE
  # ==========================================
  cyber-finance-service:
    build: ./cyber-finance-service
    container_name: cyber-finance-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server

  # ==========================================
  # MICROSERVICIO DE SURGERY
  # ==========================================
  cyber-surgery-service:
    build: ./cyber-surgery-service
    container_name: cyber-surgery-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server

  # ==========================================
  # MICROSERVICIO DE MAXTAC
  # ==========================================
  cyber-maxtac-service:
    build: ./cyber-maxtac-service
    container_name: cyber-maxtac-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server

  # ==========================================
  # MICROSERVICIO DE MAXTAC
  # ==========================================
  cyber-compatibility-service:
    build: ./cyber-compatibility-service
    container_name: cyber-compatibility-service
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server

  # ==========================================
  # API GATEWAY
  # ==========================================
  api-gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      eureka-server:
        condition: service_started


