eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/db_RIPPERDOC_CLINIC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cyber-finance-service.url = http://cyber-finance-service:8084/api/v1/billeteras
cyber-maxtac-service.url = http://cyber-maxtac-service:8087/api/v1/alertas

# CONFIGURACIÓN DE SWAGGER / OPENAPI

# Habilitar los endpoints de la documentación técnica
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Ruta del JSON interno (Firma digital para el API Gateway)
springdoc.api-docs.path=/v3/api-docs

# Ruta de acceso visual en el navegador
springdoc.swagger-ui.path=/swagger-ui.html

# Ordenamiento alfabético automático en la UI
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha